### ISSUE TITLE
How do I do Electra training (domain adaptation) with GPU

### ISSUE THREAD

**Issue by PhilipMay** [stefan-it/europeana-bert#3]
Hi Stefan,

I would like to continue training of our electra model - but not with TPU.
I want to train with GPUs to do domain adaptation. Do you have any experience with this? 
Should I use HF code or other libs like https://github.com/richarddwang/electra_pytorch or
https://ngc.nvidia.com/catalog/resources/nvidia:electra_for_tensorflow2 ?

Do you maybe have any example code or link?

Many thanks
Philip

**Comment by stefan-it** [comment]
Hi Philip,

this is a very good question! I think the original/reference implementation is not able to handle a multi-GPU setup - which is bad, because you definitely need more GPUs when training models larger than the small one.

I think it is a good to use the implementation from Richard, after reading this post:

https://discuss.huggingface.co/t/electra-training-reimplementation-and-discussion/1004

The NVIDIA recipe looks ok, but I see some potential problems, when converting the model back to HF-compatible weights. You should definitely check, if it's possible (best case it works or you have to slightly change some parameter variable names, worst case they changed the architecture, not sure how they handle generator and discriminator part).

:hugs:

**Comment by PhilipMay** [comment]
Nice. Thank you very much.
I will try that and report back.

Will close this for now.
